### ISSUE TITLE
[1.12] Crafting recipes missing

### ISSUE THREAD

**Issue by 016Nojr** [APengu/SolarFluxReborn#10]
Yeah, you broke all your crafting recipes in the latest version (3.24r)

**Comment by APengu** [comment]
No, they are there, I just moved them to JSON

**Comment by EmosewaGamer** [comment]
The problem is that JEI isn't displaying them. Also, when transfering to JSON, I believe you forgot the Draconic Cell as it still has that messed up TOAST and you can only see its recipe.

**Comment by APengu** [comment]
Draconic?

**Comment by EmosewaGamer** [comment]
The Draconic Solar Panel

**Comment by APengu** [comment]
You have draconic evolution?

**Comment by EmosewaGamer** [comment]
Yup, but no other recipe works, as you saw above.

**Comment by APengu** [comment]
Me neither :/

**Comment by EmosewaGamer** [comment]
Maybe compare your other recipes to the Draconic one as it's the only working one?

**Comment by APengu** [comment]
no, I tried and everything seems to be working :/

**Comment by EmosewaGamer** [comment]
So you're saying that the recipes are working fine in your dev environment?

**Comment by APengu** [comment]
yes, maybe it's because I messed chaotic panel? 🤔

**Comment by APengu** [comment]
bc I don't have DE in my workspace

**Comment by EmosewaGamer** [comment]
But why would every recipe besides the Draconic one work then?

**Comment by APengu** [comment]
idk. That's why I hate json recipes in 1.12 -_-

**Comment by EmosewaGamer** [comment]
They're better in some cases, worse in others.

**Comment by APengu** [comment]
yeah, I mean in my case with different cases it's really worse

**Comment by EmosewaGamer** [comment]
Did you change them manually or using the script that changes them?

**Comment by APengu** [comment]
manually

**Comment by EmosewaGamer** [comment]
Idk, try adding Draconic Evolution. The first person never specified if they had it or not.

**Comment by 016Nojr** [comment]
I do @EmosewaGamer, I forgot to mention that the draconic solar panel has its recipe.

**Comment by 016Nojr** [comment]
@APengu There is something that breaks when the recipe for the draconic solar panel is implemented. 

Disabled the Draconic Solar Panel through the SFR config, and recipes are now working fine.

Is it possible that the JSON recipes arent registered because Forge finds another way that your recipes are registered? (idk if the draconic solar panel is a JSON recipe or not)

**Comment by EmosewaGamer** [comment]
We're getting close to solving this mystery guys.

**Comment by APengu** [comment]
**ALL** recipes are now json

**Comment by EmosewaGamer** [comment]
So did you figure out where you messed up with the DE stuff?

**Comment by APengu** [comment]
nope

**Comment by APengu** [comment]
draconic solar recipe is registered last, so no idea :/

**Comment by APengu** [comment]
![image](https://user-images.githubusercontent.com/10291214/28207289-d9f9e46e-6891-11e7-89f8-7d4a8174231b.png)

**Comment by EmosewaGamer** [comment]
Wait,,, what are these Dark Matter cells/ They're before the Draconic one, so maybe they mess up the recipes before it to where only it loads up correctly.

**Comment by APengu** [comment]
no, it is integration with BlackHoleStorage, and i have it in my workspace and everything still works

**Comment by EmosewaGamer** [comment]
If there was a way to not make it last so that we could test if it has to do with it or the last one.

**Comment by APengu** [comment]
rename it inside of the jar

**Comment by APengu** [comment]
it is located here: SolarFluxReborn-3.24.jar/assets/solarfluxreborn/recipes

**Comment by EmosewaGamer** [comment]
wait.., why don't you do it? I busy with my pack atm

**Comment by 016Nojr** [comment]
I can do it, do I just rename it so it comes first alphabetically?

**Comment by APengu** [comment]
I'm busy on my other mod atm, so I'll look into that a bit later (in 1 hour)

**Comment by APengu** [comment]
yes

**Comment by EmosewaGamer** [comment]
just not last, doesn't have to be first

**Comment by 016Nojr** [comment]
Launching

**Comment by 016Nojr** [comment]
Aaaand, I made it not load. gg

**Comment by APengu** [comment]
now, can you craft chaotic panel?

**Comment by 016Nojr** [comment]
For some reason the file diseappears when I try to change the filename in Winrar (Yes, I know this isnt the correct way, but it's the only way I am able to do it)

**Comment by APengu** [comment]
did you stop your MC?

**Comment by 016Nojr** [comment]
Yeah

**Comment by EmosewaGamer** [comment]
@APengu Did you check if the Chaotic one had anything to do with it? It is before the Draconic one so it could have messed up all the recipes before it.

**Comment by 016Nojr** [comment]
I think I got it to work now, I had to change the filename to be able to edit the jar file

**Comment by 016Nojr** [comment]
That didnt fix it, only draconic solar panel.

I renamed the files so Draconic was first, then chaotic. And then the rest was default order

**Comment by EmosewaGamer** [comment]
What if you completely remove the Draconic one?

**Comment by APengu** [comment]
it should fix it, probably

**Comment by APengu** [comment]
or maybe it's bc of chaotic 🤔

**Comment by EmosewaGamer** [comment]
That's why i asked that.

**Comment by YourPapy** [comment]
Any progress?

**Comment by APengu** [comment]
nope

**Comment by YourPapy** [comment]
Hmm, I don't know anything about any of this, so I don't even know what to do to try and help.

**Comment by YourPapy** [comment]
I disabled the Chaotic solar panel in the config and all the recipes are there now. Only the Chaotic seemed to be causing issues. Maybe something with how it's crafted?

**Comment by APengu** [comment]
Okay, fixed. Enjoy ;)
