### ISSUE TITLE
[1.12] NPE Tesselation Crash in 3.25r

### ISSUE THREAD

**Issue by lrwerewolf** [APengu/SolarFluxReborn#13]
I attempted to upgrade from 3.24r to 3.25r and on loading my world, had a repeatable crash regarding a tesselation.  When I rolled back to 3.24r, the problem was resolved.  I recognize the impacted block referenced in the crash log is a Mekanism Universal Cable, but given the crash is dependent on the SFR version, felt it best to post here first.

Crashlog: https://pastebin.com/mYCxvdK9

**Comment by APengu** [comment]
This crash doesn't have my mod in stack trace thus I can't help

**Comment by lrwerewolf** [comment]
Understood.  Oddly, downgrading and re-upgrading seems to have resolved the issue.  I'll close this out.

**Comment by APengu** [comment]
This crash is a cause of CCL rendering failure
