### ISSUE TITLE
1.12 Crash

### ISSUE THREAD

**Issue by iTaeyeonKim** [APengu/SolarFluxReborn#14]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HammerCoreCore (HammerCore-1.12-1.9.4.0.jar)
  SFRCore (SolarFluxReborn_1.12-3.25r.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 9/3/17 2:20 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraftforge.items.wrapper.InvWrapper.extractItem(InvWrapper.java:166)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.extractHook(VanillaInventoryCodeHooks.java:57)
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:301)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:142)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.items.wrapper.InvWrapper.extractItem(InvWrapper.java:166)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.extractHook(VanillaInventoryCodeHooks.java:57)
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:301)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:142)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.tileentity.TileEntityHopper
	Block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-14,58,186), Chunk: (at 2,3,10 in -1,11; contains blocks -16,0,176 to -1,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: DwarfFactory
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 1246083347127634673
	Level generator: ID 07 - void, ver 0. Features enabled: true
	Level generator options: yunomakegoodmap:tree
	Level spawn location: World: (-16,64,180), Chunk: (at 0,4,4 in -1,11; contains blocks -16,0,176 to -1,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 263616 game time, 323055 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 156304 (now: false), thunder time: 113356 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 345269808 bytes (329 MB) / 1007927296 bytes (961 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 Optifine OptiFine_1.12_HD_U_C5 40 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAA	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar) 
	UCHIJAAAA	actuallyadditions{1.12.1-r119} [Actually Additions] (ActuallyAdditions-1.12.1-r119.jar) 
	UCHIJAAAA	bookshelf{2.1.429} [Bookshelf] (Bookshelf-1.12.1-2.1.429.jar) 
	UCHIJAAAA	ceramics{1.12-1.3.2} [Ceramics] (Ceramics-1.12-1.3.2.jar) 
	UCHIJAAAA	codechickenlib{3.1.2.297} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.2.297-universal (2).jar) 
	UCHIJAAAA	chickenchunks{2.4.0.70} [ChickenChunks] (ChickenChunks-1.12-2.4.0.70-universal.jar) 
	UCHIJAAAA	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCHIJAAAA	cofhcore{4.3.5} [CoFH Core] (CoFHCore-1.12-4.3.5.13-universal.jar) 
	UCHIJAAAA	cofhworld{1.0.1} [CoFH World] (CoFHWorld-1.12-1.0.1.8-universal.jar) 
	UCHIJAAAA	waila{1.8.20} [Waila] (Hwyla-1.8.20-B35_1.12.jar) 
	UCHIJAAAA	jei{4.7.5.85} [Just Enough Items] (jei_1.12-4.7.5.85.jar) 
	UCHIJAAAA	darkutils{1.7.169} [Dark Utilities] (DarkUtils-1.12.1-1.7.169.jar) 
	UCHIJAAAA	exnihilocreatio{1.12-0.1.3} [Ex Nihilo Creatio] (exnihilocreatio-1.12-0.1.3.jar) 
	UCHIJAAAA	excompressum{3.0.4} [Ex Compressum] (ExCompressum_1.12.1-3.0.4.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.6.jar) 
	UCHIJAAAA	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.12-2.4.0.231-universal.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-4.0.5.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-4.0.3.jar) 
	UCHIJAAAA	grue{1.3.5} [Grue] (Grue-1.12-1.3.5.jar) 
	UCHIJAAAA	hammercore{1.9.4.0} [Hammer Core] (HammerCore-1.12-1.9.4.0.jar) 
	UCHIJAAAA	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	neat{1.4-15} [Neat] (Neat 1.4-15.jar) 
	UCHIJAAAA	oreexcavation{1.4.104} [OreExcavation] (OreExcavation-1.4.104.jar) 
	UCHIJAAAA	thermalfoundation{2.3.5} [Thermal Foundation] (ThermalFoundation-1.12-2.3.5.14-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.3.5} [Thermal Expansion] (ThermalExpansion-1.12-5.3.5.19-universal.jar) 
	UCHIJAAAA	redstonearsenal{2.3.5} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.5.13-universal.jar) 
	UCHIJAAAA	solarfluxreborn{3.25r} [Solar Flux Reborn] (SolarFluxReborn_1.12-3.25r.jar) 
	UCHIJAAAA	beneath{1.2.0} [The Beneath] (The Beneath-1.12-1.2.0.jar) 
	UCHIJAAAA	thermaldynamics{2.3.5} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.5.12-universal.jar) 
	UCHIJAAAA	tp{1.12} [Tiny Progressions] (tinyprogressions-1.12-3.2.6.jar) 
	UCHIJAAAA	ts2k16{1.2.5} [Twerk-Sim 2K16] (TS2K16-1.2.5.jar) 
	UCHIJAAAA	wawla{2.5.240} [What Are We Looking At] (Wawla-1.12.1-2.5.240.jar) 
	UCHIJAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJAAAA	yunomakegoodmap{1.12-6.3.0.28} [YUNoMakeGoodMap] (YUNoMakeGoodMap-1.12-6.3.0.28.jar) 
	UD	solarfluxreborncore{3.25r} [Solar Flux Reborn: Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
HammerCoreCore (HammerCore-1.12-1.9.4.0.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
SFRCore (SolarFluxReborn_1.12-3.25r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12_HD_U_C5
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.14008 Compatibility Profile Context 21.19.137.1
	OpenGlRenderer: AMD Radeon R7 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by APengu** [comment]
I'm sorry, but why are you reporting this crash to me? It doesn't have anything to do with SFR...
