### ISSUE TITLE
Crash with Hammer Core update (1.9.4.4)

### ISSUE THREAD

**Issue by FnordMan** [APengu/SolarFluxReborn#16]
The changelog for Hammer Core v1.9.4.4 warns about a bunch of changes and that mods will need to be updated. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-71.jar)
  CoreMod (Aroma1997Core-1.12.1-1.3.0.0.b122.jar)
  AppleCore (AppleCore-mc1.12.1-2.2.2.jar)
  HammerCoreCore (HammerCore-1.12.1-1.9.4.4.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.0-beta2-1.12-anarchy.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  LoadingPlugin (NoNausea-MC1.12-1.0.jar)
  LoadingPlugin (RandomThings-MC1.12.1-4.0.5.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 9/6/17 6:41 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Solar Flux Reborn (solarfluxreborn)
Caused by: java.lang.NoClassDefFoundError: com/pengu/hammercore/client/render/item/IItemRender
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:586)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.pengu.hammercore.client.render.item.IItemRender
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2018715824 bytes (1925 MB) / 3177185280 bytes (3030 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2G -Xmx5G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.41 Powered by Forge 14.22.0.2469 152 mods loaded, 152 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version            | Source                                            | Signature                                |
	|:----- |:------------------------ |:------------------ |:------------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft                | 1.12.1             | minecraft.jar                                     | None                                     |
	| UC    | mcp                      | 9.19               | minecraft.jar                                     | None                                     |
	| UC    | FML                      | 8.0.99.99          | forge-1.12.1-14.22.0.2469.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                    | 14.22.0.2469       | forge-1.12.1-14.22.0.2469.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | foamfixcore              | 7.7.4              | minecraft.jar                                     | None                                     |
	| UC    | actuallyadditions        | 1.12.1-r119        | ActuallyAdditions-1.12.1-r119.jar                 | None                                     |
	| UC    | baubles                  | 1.5.1              | Baubles-1.12-1.5.1.jar                            | None                                     |
	| UC    | actuallybaubles          | 1.1                | ActuallyBaubles-1.12-1.1.jar                      | None                                     |
	| UC    | chisel                   | MC1.12-0.0.13.16   | Chisel-MC1.12-0.0.13.16.jar                       | None                                     |
	| UC    | crafttweaker             | 4.0.5              | CraftTweaker2-1.12-4.0.5.jar                      | None                                     |
	| UC    | mtlib                    | @VERSION@          | MTLib-3.0.0.jar                                   | None                                     |
	| UC    | modtweaker               | 4.0.1              | modtweaker-4.0.1.jar                              | None                                     |
	| UC    | jei                      | 4.7.8.92           | jei_1.12.1-4.7.8.92.jar                           | None                                     |
	| UC    | mantle                   | 1.12-1.3.1.21      | Mantle-1.12-1.3.1.21.jar                          | None                                     |
	| UC    | tconstruct               | 1.12-2.7.3.30      | TConstruct-1.12-2.7.3.30.jar                      | None                                     |
	| UC    | extrautils2              | 1.0                | extrautils2-1.12-1.6.1.jar                        | None                                     |
	| UC    | flyringbaublemod         | 0.3.0_1.12-306787e | angelRingToBauble-1.12-0.3.0.46+306787e.jar       | None                                     |
	| UC    | applecore                | 2.2.2              | AppleCore-mc1.12.1-2.2.2.jar                      | None                                     |
	| UC    | appleskin                | 1.0.7              | AppleSkin-mc1.12-1.0.7.jar                        | None                                     |
	| UC    | appliedenergistics2      | rv5-alpha-4        | appliedenergistics2-rv5-alpha-4.jar               | None                                     |
	| UC    | aroma1997core            | 1.3.0.0.b122       | Aroma1997Core-1.12.1-1.3.0.0.b122.jar             | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UC    | aroma1997sdimension      | 1.3.0.0.b37        | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar | None                                     |
	| UC    | psi                      | r1.1-52            | Psi-r1.1-52.jar                                   | None                                     |
	| UC    | autoreglib               | 1.3-13             | AutoRegLib-1.3-13.jar                             | None                                     |
	| UC    | bdlib                    | 1.14.1.6           | bdlib-1.14.1.6-mc1.12.jar                         | None                                     |
	| UC    | betterbuilderswands      | 0.11.1             | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar   | None                                     |
	| UC    | forestry                 | 5.5.2.185          | forestry_1.12.1-5.5.2.185.jar                     | None                                     |
	| UC    | binniecore               | unspecified        | binnie-mods-1.12.1-2.3.0.60.jar                   | None                                     |
	| UC    | binniedesign             | 1.0                | binnie-mods-1.12.1-2.3.0.60.jar                   | None                                     |
	| UC    | genetics                 | 2.3.0.60           | binnie-mods-1.12.1-2.3.0.60.jar                   | None                                     |
	| UC    | botany                   | 2.3.0.60           | binnie-mods-1.12.1-2.3.0.60.jar                   | None                                     |
	| UC    | extrabees                | 2.3.0.60           | binnie-mods-1.12.1-2.3.0.60.jar                   | None                                     |
	| UC    | extratrees               | 2.3.0.60           | binnie-mods-1.12.1-2.3.0.60.jar                   | None                                     |
	| UC    | bookshelf                | 2.1.433            | Bookshelf-1.12.1-2.1.433.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | botania                  | r1.10-347          | Botania r1.10-347.jar                             | None                                     |
	| UC    | codechickenlib           | 3.1.1.288          | CodeChickenLib-1.12-3.1.1.288-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | redstoneflux             | 2.0.1              | RedstoneFlux-1.12-2.0.1.2-universal.jar           | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UC    | brandonscore             | 2.3.2              | BrandonsCore-1.12-2.3.2.129-universal.jar         | None                                     |
	| UC    | ceramics                 | 1.12-1.3.2         | Ceramics-1.12-1.3.2.jar                           | None                                     |
	| UC    | chameleon                | 1.12-4.1.3         | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| UC    | chancecubes              | 1.12.1-3.0.1.203   | ChanceCubes-1.12.1-3.0.1.203.jar                  | None                                     |
	| UC    | chesttransporter         | 2.8.7              | ChestTransporter-1.12-2.8.7.jar                   | None                                     |
	| UC    | chickenchunks            | 2.4.0.70           | ChickenChunks-1.12-2.4.0.70-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | chiselsandbits           | 14.7               | chiselsandbits-14.7.jar                           | None                                     |
	| UC    | cofhcore                 | 4.3.5              | CoFHCore-1.12-4.3.5.13-universal.jar              | None                                     |
	| UC    | cofhworld                | 1.0.1              | CoFHWorld-1.12-1.0.1.8-universal.jar              | None                                     |
	| UC    | cyclopscore              | 0.10.17            | CyclopsCore-1.12-0.10.17.jar                      | None                                     |
	| UC    | commoncapabilities       | 1.4.0              | CommonCapabilities-1.12-1.4.0.jar                 | None                                     |
	| UC    | compactmachines3         | 3.0.0              | compactmachines3-1.12.1-3.0.0-b127.jar            | None                                     |
	| UC    | computality              | 1.82.3             | computality-1.12-1.82.3.jar                       | None                                     |
	| UC    | controlling              | 3.0.2              | Controlling-3.0.2.jar                             | None                                     |
	| UC    | cookingforblockheads     | 6.3.6              | CookingForBlockheads_1.12.1-6.3.6.jar             | None                                     |
	| UC    | ctgui                    | 1.0.0              | CraftTweaker2-1.12-4.0.5.jar                      | None                                     |
	| UC    | crafttweakerjei          | 2.0.0              | CraftTweaker2-1.12-4.0.5.jar                      | None                                     |
	| UC    | ctdcore                  | 1.1.6              | CTD-Core-1.12.1-1.1.6.jar                         | None                                     |
	| UC    | ctdtweaks                | 1.5.10             | CTD-Tweaks-1.12-1.5.10.jar                        | None                                     |
	| UC    | ctm                      | MC1.12-0.2.2.7     | CTM-MC1.12-0.2.2.7.jar                            | None                                     |
	| UC    | cucumber                 | 1.0.2              | cucumber[1.12]-1.0.2.jar                          | None                                     |
	| UC    | cyclicmagic              | 1.8.0              | Cyclic-1.12-1.8.0.jar                             | None                                     |
	| UC    | waila                    | 1.8.20             | Hwyla-1.8.20-B35_1.12.jar                         | None                                     |
	| UC    | darkutils                | 1.7.169            | DarkUtils-1.12.1-1.7.169.jar                      | None                                     |
	| UC    | draconicevolution        | 2.3.3              | Draconic-Evolution-1.12-2.3.3.261-universal.jar   | None                                     |
	| UC    | elevatorid               | 1.3.4              | ElevatorMod-1.12-1.3.4.jar                        | None                                     |
	| UC    | enderstorage             | 1.0                | EnderStorage-1.12-2.4.0.119-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | enderutilities           | 0.7.3              | enderutilities-1.12.0-0.7.3.jar                   | None                                     |
	| UC    | energyconverters         | 1.0.1.2            | energyconverters_1.12.1-1.0.1.2.jar               | None                                     |
	| UC    | valkyrielib              | 1.12-2.0.1a        | valkyrielib-1.12.1-2.0.2c.jar                     | None                                     |
	| UC    | environmentaltech        | 1.12.1-2.0.2d      | environmentaltech-1.12.1-2.0.2d.jar               | None                                     |
	| UC    | mekanism                 | 9.4.1              | Mekanism-1.12.1-9.4.1.326.jar                     | None                                     |
	| UC    | thermalfoundation        | 2.3.5              | ThermalFoundation-1.12-2.3.5.14-universal.jar     | None                                     |
	| UC    | thermalexpansion         | 5.3.5              | ThermalExpansion-1.12-5.3.5.19-universal.jar      | None                                     |
	| UC    | exchangers               | 1.12-2.4           | Exchangers-1.12-2.4.jar                           | None                                     |
	| UC    | exnihilocreatio          | 1.12-0.1.3         | exnihilocreatio-1.12-0.1.3.jar                    | None                                     |
	| UC    | zerocore                 | 1.12-0.1.0.9       | zerocore-1.12-0.1.0.9.jar                         | None                                     |
	| UC    | bigreactors              | 1.12-0.4.5.34      | ExtremeReactors-1.12-0.4.5.34.jar                 | None                                     |
	| UC    | ffs                      | 1.12-2.1.2         | Fancy Fluid Storage-1.12-2.1.3.jar                | None                                     |
	| UC    | fastleafdecay            | v14                | FastLeafDecay-v14.jar                             | None                                     |
	| UC    | foamfix                  | 0.8.0-beta2-1.12   | foamfix-0.8.0-beta2-1.12-anarchy.jar              | None                                     |
	| UC    | forgelin                 | 1.5.1              | Forgelin-1.5.1.jar                                | None                                     |
	| UC    | ftbl                     | 0.0.0              | FTBLib-4.0.5.jar                                  | None                                     |
	| UC    | ftbu                     | 0.0.0              | FTBUtilities-4.0.3.jar                            | None                                     |
	| UC    | gendustry                | 1.6.5.4            | gendustry-1.6.5.4-mc1.12.jar                      | None                                     |
	| UC    | pressure                 | 1.3.1.2            | pressure-1.3.1.2-mc1.12.jar                       | None                                     |
	| UC    | advgenerators            | 0.9.20.5           | generators-0.9.20.5-mc1.12.jar                    | None                                     |
	| UC    | gogskybox                | 1.1-3              | GoGSkybox 1.1-3.jar                               | None                                     |
	| UC    | gravestone               | 1.9.0              | gravestone-1.9.0.jar                              | None                                     |
	| UC    | hammercore               | 1.9.4.4            | HammerCore-1.12.1-1.9.4.4.jar                     | None                                     |
	| UC    | theoneprobe              | 1.4.18             | theoneprobe-1.12-1.4.18.jar                       | None                                     |
	| UC    | immersiveengineering     | 0.12-71            | ImmersiveEngineering-0.12-71.jar                  | None                                     |
	| UC    | immersivepetroleum       | 1.1.3              | immersivepetroleum-1.12-1.1.3.jar                 | None                                     |
	| UC    | immersivetech            | 1.3.1              | immersivetech-1.12-1.3.1.jar                      | None                                     |
	| UC    | teslacorelib             | 1.0.8              | tesla-core-lib-1.12-1.0.8.jar                     | None                                     |
	| UC    | industrialforegoing      | 1.12-1.12          | industrialforegoing-1.12-1.2.1-48.jar             | None                                     |
	| UC    | initialinventory         | 2.0.2              | InitialInventory-3.0.0.jar                        | None                                     |
	| UC    | integrateddynamics       | 0.8.7              | IntegratedDynamics-1.12-0.8.7.jar                 | None                                     |
	| UC    | integrateddynamicscompat | 1.0.0              | IntegratedDynamics-1.12-0.8.7.jar                 | None                                     |
	| UC    | integratedtunnels        | 1.3.2              | IntegratedTunnels-1.12-1.3.2.jar                  | None                                     |
	| UC    | ironchest                | 1.12-7.0.31.818    | ironchest-1.12-7.0.31.818.jar                     | None                                     |
	| UC    | journeymap               | 1.12.1-5.5.0b3     | journeymap-1.12.1-5.5.0b3.jar                     | None                                     |
	| UC    | justanothersnad          | 1.12-1.0.0.0       | JustAnotherSnad-1.12-1.0.0.0.jar                  | None                                     |
	| UC    | jeresources              | 0.8.4.24           | JustEnoughResources-1.12.1-0.8.4.24.jar           | None                                     |
	| UC    | kleeslabs                | 5.3.2              | KleeSlabs_1.12-5.3.2.jar                          | None                                     |
	| UC    | llor                     | 1.1.4-mc1.12       | LLOverlayReloaded-1.1.4-mc1.12.jar                | None                                     |
	| UC    | lostcities               | 1.0.0              | lostcities-1.12-1.0.0.jar                         | None                                     |
	| UC    | mekanismgenerators       | 9.4.1              | MekanismGenerators-1.12.1-9.4.1.326.jar           | None                                     |
	| UC    | mekanismtools            | 9.4.1              | MekanismTools-1.12.1-9.4.1.326.jar                | None                                     |
	| UC    | mob_grinding_utils       | 0.3.2              | MobGrindingUtils-0.3.2.jar                        | None                                     |
	| UC    | modnametooltip           | 1.9.0              | modnametooltip_1.12.1-1.9.0.jar                   | None                                     |
	| UC    | morpheus                 | 1.12-3.3.2         | Morpheus-1.12-3.3.2.jar                           | None                                     |
	| UC    | mysticalagriculture      | 1.6.3              | mysticalagriculture[1.12]-1.6.3.jar               | None                                     |
	| UC    | mysticalagradditions     | 1.2.4              | mysticalagradditions[1.12]-1.2.4.jar              | None                                     |
	| UC    | nofov                    | 1.0.1              | NoFov-MC1.12-1.0.1.jar                            | None                                     |
	| UC    | nonausea                 | 1.0                | NoNausea-MC1.12-1.0.jar                           | None                                     |
	| UC    | notenoughwands           | 1.5.9              | notenoughwands-1.12-1.5.9.jar                     | None                                     |
	| UC    | oreexcavation            | 1.4.105            | OreExcavation-1.4.105.jar                         | None                                     |
	| UC    | harvestcraft             | 1.12.1b            | Pam's HarvestCraft 1.12.1b.jar                    | None                                     |
	| UC    | projecte                 | 1.12-PE1.1.0       | ProjectE-1.12-PE1.1.0.jar                         | None                                     |
	| UC    | plustic                  | 6.3.1.2            | plustic-6.3.1.2.jar                               | None                                     |
	| UC    | reborncore               | 3.3.0.99           | RebornCore-1.12.1-3.3.0.99-universal.jar          | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UC    | quantumstorage           | 4.4.0              | QuantumStorage-1.12-4.4.0.jar                     | None                                     |
	| UC    | randomthings             | 4.0.5              | RandomThings-MC1.12.1-4.0.5.jar                   | None                                     |
	| UC    | rangedpumps              | 0.5                | rangedpumps-0.5.jar                               | None                                     |
	| UC    | storagedrawers           | 1.12-5.2.5         | StorageDrawers-1.12.1-5.3.1.jar                   | None                                     |
	| UC    | refinedstorage           | 1.5.17             | refinedstorage-1.5.17.jar                         | None                                     |
	| UC    | rebornstorage            | 1.0.0              | RebornStorage-1.12-2.0.1.6.jar                    | None                                     |
	| UC    | redstonearsenal          | 2.3.5              | RedstoneArsenal-1.12-2.3.5.13-universal.jar       | None                                     |
	| UC    | xreliquary               | 1.12-1.3.4.710     | Reliquary-1.12-1.3.4.710.jar                      | None                                     |
	| UC    | resourceloader           | 1.5.2              | ResourceLoader-MC1.12-1.5.2.jar                   | None                                     |
	| UC    | rftools                  | 6.13               | rftools-1.12-6.13.jar                             | None                                     |
	| UC    | rftoolscontrol           | 1.6.8              | rftoolsctrl-1.12-1.6.8.jar                        | None                                     |
	| UC    | rftoolsdim               | 5.04               | rftoolsdim-1.12-5.04.jar                          | None                                     |
	| UC    | signal-catcher           | 1.1                | signalcatcher-1.1.jar                             | None                                     |
	| UC    | simplesponge             | 3.5                | SimpleSponge-1.12-3.5.jar                         | None                                     |
	| UC    | simplyenchanting         | 1.0.3              | SimplyEnchanting-1.12-1.0.3.jar                   | None                                     |
	| UE    | solarfluxreborn          | 3.25r              | SolarFluxReborn_1.12-3.25r.jar                    | None                                     |
	| UC    | soulshardstow            | 1.12-2.7.3-52      | SoulShards-TOW-1.12-2.7.3-52.jar                  | None                                     |
	| UC    | stevescarts              | ${version}         | StevesCarts-1.12.1-2.4.8.44.jar                   | None                                     |
	| UC    | techreborn               | 2.7.0.205          | TechReborn-1.12.1-2.7.0.205-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UC    | thermalcultivation       | 0.1.1              | ThermalCultivation-1.12-0.1.1.6-universal.jar     | None                                     |
	| UC    | thermaldynamics          | 2.3.5              | ThermalDynamics-1.12-2.3.5.12-universal.jar       | None                                     |
	| UC    | tinkersaddons            | 1.0.6              | Tinkers' Addons-1.12-1.0.6.jar                    | None                                     |
	| UC    | tp                       | 1.12               | tinyprogressions-1.12-3.2.6.jar                   | None                                     |
	| UC    | topaddons                | 1.12-0.15.1        | topaddons-1.12-0.15.1.jar                         | None                                     |
	| UC    | torchmaster              | 1.5.3.43           | torchmaster_1.12.1-1.5.3.43.jar                   | None                                     |
	| UC    | universalremote          | 1.12-0.9.2         | UniversalRemote-1.12-0.9.2.jar                    | None                                     |
	| UC    | usefulnullifiers         | 1.4.1              | usefulnullifiers-1.4.1.jar                        | None                                     |
	| UC    | wailaharvestability      | 1.1.11             | WailaHarvestability-mc1.12-1.1.11.jar             | None                                     |
	| UC    | waterstrainer            | 3.2.0              | WaterStrainer-1.12-3.2.0.jar                      | None                                     |
	| UC    | wawla                    | 2.5.241            | Wawla-1.12.1-2.5.241.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | xnet                     | 1.4.0              | xnet-1.12-1.4.0.jar                               | None                                     |
	| UC    | yunomakegoodmap          | 1.12-6.3.0.28      | YUNoMakeGoodMap-1.12-6.3.0.28.jar                 | None                                     |
	| UC    | teslacorelib_registries  | 1.0.8              | tesla-core-lib-1.12-1.0.8.jar                     | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  lumien.resourceloader.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.5.1.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-71.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CoreMod (Aroma1997Core-1.12.1-1.3.0.0.b122.jar)
  
AppleCore (AppleCore-mc1.12.1-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
HammerCoreCore (HammerCore-1.12.1-1.9.4.4.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.0-beta2-1.12-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (NoNausea-MC1.12-1.0.jar)
  lumien.nonausea.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.12.1-4.0.5.jar)
  lumien.randomthings.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.28' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	AE2 Version: alpha rv5-alpha-4 for Forge 14.21.1.2412

**Comment by APengu** [comment]
Did you read HammerCore changelogs? I said that the mod must be updated!
