### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by 0dikpah** [APengu/SolarFluxReborn#18]
I don't know if it's this mod causing the crash but i upload crashreport anyways.
Hope you can help me.

Minecraft 1.12.1
Forge 1.12.1-14.22.1.2485
SolarFluxReborn_1.12.1-3.40r
[crash-2017-09-24_15.29.55-server.txt](https://github.com/APengu/SolarFluxReborn/files/1327344/crash-2017-09-24_15.29.55-server.txt)

**Comment by APengu** [comment]
This is IE and AA
