### ISSUE TITLE
[1.12.1] Recipes Missing, Config gets "ignored" and log errors.

### ISSUE THREAD

**Issue by UnPure** [APengu/SolarFluxReborn#19]
Hey there. I currently have a few issues with SolarFluxReborn.

1. All upgrades that are available have no recipes that are shown in JEI. The solar panels have recipes and are working fine.

2. I saw that in the config the solar panel tier 8 is set to false but still its possible to craft and use that solar panel.

3. While starting a server/client i get an error/warning in the logs.

    [Server thread/WARN] [solarfluxreborncore]: Mod solarfluxreborncore has been disabled through configuration

All configs are default, nothing is changed.

4. The cables are causing a lot of visual bugs. Most of the time they are transparent and while they are part of the base, most other stuff gets transparent too (for example minecraft chests). This stops as soon as there are no more cables placed. 
Maybe this is fixed in the latest version because they are changed from TESR to models. If thats the case, feel free to ignore this part.

**SolarFluxReborn:** 3.40r
**Forge:** 14.22.0.2475

**Comment by APengu** [comment]
1. I clearly stated that updrades are WIP. They don't work. Thus I had to remove recipes for them.
2. The counting starts from zero, so your "panel 8" is actually "panel 9" ingame. But you see the panel Tier VIII (solar7 in configs).
3. This is the actual ASM core of the mod. It's required to get some stuff done and doesn't have to be enabled as a mod. (You can safely ignore that issue)
4. Yes, this was fixed a version ago.

So mostly it's just a misunderstanding the stuff...
