### ISSUE TITLE
[1.10.2] SkyFactory 3 ModPack - Can't place Upgrades

### ISSUE THREAD

**Issue by Kayepur** [APengu/SolarFluxReborn#24]
When using Solar Flux Reborn mod in this pack,(and maybe by itself, not tested), I can not place any upgrades into any of the panels. I tried even in creative mode. Looked it up on Reddit, and no one opened a ticket to date.

Sky Factory 3 vs. 3.0.15
Solar Flux 1.10.2-2.17r

**Comment by APengu** [comment]
1) This is intentional
2) 1.10.2 is no longer officially supported.

**Comment by Tyranuss** [comment]
I'm sorry but can you explain why is it intentional?? Like why did u even put those upgrades in the first place? I don't get it. Make a mod and then intentionally disables the part of the mod?

**Comment by kpeckett** [comment]
So it's basically a troll. Make expensive upgrades that can't do anything.

**Comment by APengu** [comment]
I'm so annoyed with these upgrades! GOSH
