### ISSUE TITLE
Crashed with solar flux

### ISSUE THREAD

**Issue by Zdyzeus** [APengu/SolarFluxReborn#25]
So, I got an error while trying to use solar flux in my private modpack, with this error: 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Solar Flux Reborn (solarfluxreborn)

Here's the crash report .txt. 
[crash-2017-11-03_15.30.09-client.txt](https://github.com/APengu/SolarFluxReborn/files/1442397/crash-2017-11-03_15.30.09-client.txt)
Thank you!

**Comment by APengu** [comment]
This is due to changes in HammerCore in 1.10.2 due to changes it got. This is not fixable unless you downgrade Hammer Core to older builds.

**Comment by Zdyzeus** [comment]
How old of a build are we talking? I'm running on 1.10.2, with hammer core 1.9.4.3. A few releases or a whole version?
