### ISSUE TITLE
Exception loading model/blockstate

### ISSUE THREAD

**Issue by mankra** [APengu/SolarFluxReborn#27]
https://pastebin.com/j7gWbeyL

It seems there are files missing, e.g.

> Caused by: java.io.FileNotFoundException: solarfluxreborn:models/item/solar0.json

Minecraft: 1.12.2
Forge: 14.23.1.2554
Solar Flux Reborn: 3.42r
Hammer Core: 1.9.5.5

**Comment by APengu** [comment]
It's normal. Just ignore that.

**Comment by mankra** [comment]
No, it's not normal. I have 80 mods in my modpack and about 4 or 5 with this error.

There's a reason for that message and a reason for calling it an ERROR. Ignoring error messages is just bad practice.

If you think the reason for that error message is not good, then please give me a good argument why that's the case, so I can talk to the forge people about removing that error message.

**Comment by APengu** [comment]
Because I don't use models. I use rendering instead. It's better for "solarThickness" parameter thus I can't use vanilla json models

**Comment by mankra** [comment]
Ok, to get it right: You say there's a case where it's normal to not have a correspondig json file when not using models but rendering. Therefore it should not be necessary to log that error message, right?

How can this case be recognized by forge? Seems it's looking for the json files no matter what.

What about the blockstate error:

> Caused by: java.io.FileNotFoundException: solarfluxreborn:blockstates/solar6.json

Same reason as for the models?

**Comment by mankra** [comment]
> He could simply add a empty json and there error should be away. I don't think that forge implements a method to disable this for special blocks/items

**Comment by mankra** [comment]
> This isn't an issue

It is an issue. There are error messages in the log caused by your mod. There are ways to prevent these error messages.

Any software bloating the log file with untreated errors is bad software, no matter wether it's working or not.

You can make it better.
