### ISSUE TITLE
null error randomly

### ISSUE THREAD

**Issue by JoeSGT** [APengu/SolarFluxReborn#29]
i get this null error and it happen's randomly
here is the error https://pastebin.com/5k3Hx6Ku
and my version's are 
- forge-1.12.2-14.23.1.2562
- HammerCore-1.12.2-1.9.5.7
- SolarFluxReborn_1.12.2-3.42r

**Comment by APengu** [comment]
Report this to sponge.

**Comment by JoeSGT** [comment]
okay i would but i would like to know how to reproduce this bug 
do you know what it could be?

**Comment by APengu** [comment]
it's probably EU2 wireless emitter attempting to make a connection to SFR panels
