### ISSUE TITLE
Client Crashes

### ISSUE THREAD

**Issue by Sclane1** [APengu/SolarFluxReborn#35]
Hello,
i created a Modpack for MC 1.12.2
and use SolarFluxReborn Version 3.42r
Hammercore 1.9.6.3
Draconic Evolution 2.3.8.279-universal

and in the loding phase 3 of the Client where he loads the models form the mods crashes the Game.

I hope someone can help me and sry, when it is a other problem, but by SolarFluxReborn only "UC" all other with "UCH"

[crash-2018-01-21_16.07.23-client.txt](https://github.com/APengu/SolarFluxReborn/files/1649850/crash-2018-01-21_16.07.23-client.txt)

Thanks
Sclane1

**Comment by APengu** [comment]
This crash is caused by TConstruct.
