### ISSUE TITLE
Issue with playerloggedin?!?

### ISSUE THREAD

**Issue by NicosaurusRex99** [APengu/SolarFluxReborn#36]
crash occurs on loadup
sf version 1.12.2-3.42r
https://pastebin.com/UDuVKLnd

**Comment by pinocchiowasjew** [comment]
Ditto. The issue is caused by the newest version of Hammer Core (1.9.6.7). I suggest using 1.9.6.5 for now.

**Comment by APengu** [comment]
Oki, fixed in 3.50r
