### ISSUE TITLE
Exception in server tick loop [1.12.2]

### ISSUE THREAD

**Issue by Fundryi** [APengu/SolarFluxReborn#37]
Minecraft 1.12.2
Forge: 14.23.2.2619

[Small Crash Log](https://pastebin.com/raw/w3pQynw1)
[Full Crash File](https://github.com/APengu/SolarFluxReborn/files/1756025/crash-2018-02-25_13.42.32-server.txt)

**Comment by APengu** [comment]
This is old issue and it has been fixed.

**Comment by Fundryi** [comment]
Fixed in dev I guess. When will the Updated be out? Thanks.

**Comment by APengu** [comment]
It is already released, waiting on approval.

**Comment by Fundryi** [comment]
Cool thank you so much!
