### ISSUE TITLE
[1.12] Upgrades inserted into solar panels vanish

### ISSUE THREAD

**Issue by 016Nojr** [APengu/SolarFluxReborn#9]
Upgrades inserted into the solar panel (Tested with Tier 5) vanish when moved into the inventory.

Mod versions:
SFR: 3.24r
Forge: 14.21.1.2407

Modlist can be provided if wanted

**Comment by APengu** [comment]
upgrades are disabled at all ._.

**Comment by APengu** [comment]
yes. they are not working in 1.12 at all

**Comment by 016Nojr** [comment]
oh
